"use client";

import Link from "next/link";
import "./globals.css"
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };


const navLinks = [
  {name:"Register", href:"/register"},
  {name:"Login", href:"/login"},
  {name:"Forgot Password", href:"/forgot-password"}
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <div className="flex space-x-1">
            {navLinks.map((link)=>{
              const isActive = pathname === link.href || (pathname.startsWith(link.href) && link.href !== "/");
              return(
                <Link className={isActive ? "font-bold" : "text-blue-500"} href={link.href} key={link.name}>
                {link.name}
                </Link>
              );
            })}
          </div>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
